name: adhdo_it_mob
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter


  # Навигация
  go_router: ^15.1.1  
  

  # UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  flutter_bounceable: ^1.2.0
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  image_cropper: ^9.1.0
  connectivity_plus: ^6.1.4
  gap: ^3.0.1
  google_fonts: ^6.2.1
  mask_text_input_formatter: ^2.9.0
  loading_indicator: ^3.1.1
  toastification: ^3.0.2
  pin_code_fields: ^8.0.1
  pinput: ^5.0.1

  # Localizations
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # State Management
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Data and Storage
  dio: ^5.8.0+1
  tf_dio_cache: ^1.0.2
  shared_preferences: ^2.5.3
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  # Push notification 
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.1.0
  firebase_core: ^3.13.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.5




  # Icon Generator
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  image_path: "assets/images/logo.png"  
  android: true
  ios: true  

flutter:
  generate: true  
  uses-material-design: true


  assets:
    - assets/images/
    - assets/svg/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
